#!/bin/bash
# Based off
# https://github.com/tmux-plugins/tmux-battery
battery_status() {
	if type 'pmset' >/dev/null 2>&1; then
		pmset -g batt | awk -F '; *' 'NR==2 { print $2 }'
	elif type 'upower' >/dev/null 2>&1; then
		# sort order: attached, charging, discharging
		for battery in $(upower -e | grep battery); do
			upower -i $battery | grep state | awk '{print $2}'
		done | sort | head -1
	elif type 'acpi' >/dev/null 2>&1; then
		acpi -b | grep -oi 'discharging' | awk '{print tolower($0)}'
	fi
}
battery_percent() {
	# percentage displayed in the 2nd field of the 2nd row
	if type 'pmset' >/dev/null 2>&1; then
		pmset -g batt | grep -o "[0-9]\{1,3\}%"
	elif type 'upower' >/dev/null 2>&1; then
		local batteries=( $(upower -e | grep battery) )
		local energy
		local energy_full
		for battery in ${batteries[@]}; do
			energy=$(upower -i $battery | awk -v nrg="$energy" '/energy:/ {print nrg+$2}')
			energy_full=$(upower -i $battery | awk -v nrgfull="$energy_full" '/energy-full:/ {print nrgfull+$2}')
		done
		echo $energy $energy_full | awk '{printf("%d%%", ($1/$2)*100)}'
	elif type 'acpi' >/dev/null 2>&1; then
		acpi -b | grep -Eo "[0-9]+%"
	fi
}
battery_graph() {
    tmp=$(battery_percent)
    percent=${tmp%?}
	if [ -z "$percent" ]; then
		echo ''
	elif [ "$percent" -lt "20" ]; then
		echo '▁'
	elif [ "$percent" -lt "40" ]; then
		echo '▂'
	elif [ "$percent" -lt "60" ]; then
		echo '▃'
	elif [ "$percent" -lt "80" ]; then
		echo '▅'
	else
		echo '▇'
	fi
}
battery_color() {
    status=$(battery_status)
    if [[ $status =~ (^charging) ]]; then
        if [[ "$1" == 'tmux' ]]; then
            echo '#[fg=green]'
        else
            echo -e '\033[0;32m'
        fi
    else
        tmp=$(battery_percent)
        percent=${tmp%?}
        if [ "$percent" -lt "25" ]; then
            if [[ "$1" == 'tmux' ]]; then
                echo '#[fg=red]'
            else
                echo -e '\033[0;31m'
            fi
        else
            if [[ "$1" == 'tmux' ]]; then
                echo '#[default]'
            else
                echo -e '\033[0m'
            fi
        fi
    fi
}
battery_tmux() {
    echo "$(battery_percent) $(battery_color tmux)$(battery_graph)#[default]"
}
battery_zsh() {
    echo -e "$(battery_percent) %{$(battery_color)%}$(battery_graph)%{\033[0m%}"
}

if ! [ -z "$1" ]; then
    eval "battery_$1"
else
    echo -e "$(battery_percent) $(battery_color)$(battery_graph)\033[0m"
fi
